<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Sorting
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>

<?php
$helper = $block->getData('osc_helper') ?>

<div class="one-step-checkout onestepcheckout-index-index <?php echo $helper->getLayoutClass() ?> clearfix">
    <div id="checkout" data-bind="scope:'checkout'" class="checkout-container md-checkout">
        <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
            <div class="loader">
                <img src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Mavenbird_OneStepCheckout/images/loader-1.gif'); ?>"
                     alt="<?php /* @escapeNotVerified */ echo __('Loading...'); ?>"
                     style="position: absolute;">
            </div>
        </div>
        <div class="osc-heading">
            <h1><?php echo $helper->getCheckoutTitle() ?></h1>
            <p><?php echo $helper->getCheckoutDescription() ?></p>
        </div>
        <!-- ko template: getTemplate() --><!-- /ko -->
        <script type="text/x-magento-init">
            {
                "#checkout": {
                    "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>
                }
            }
        </script>
        <script>
            window.checkoutConfig = <?php /* @escapeNotVerified */ echo \Zend_Json::encode($block->getCheckoutConfig()); ?>;
            window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
            window.customerData = window.checkoutConfig.customerData;

        </script>
        <script>
            require([
                'mage/url',
                'Magento_Ui/js/block-loader'
            ], function(url, blockLoader) {
                blockLoader("<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Mavenbird_OneStepCheckout/images/block-loader-1.gif'); ?>");
                return url.setBaseUrl('<?php /* @escapeNotVerified */ echo $block->getBaseUrl();?>');
            })
        </script>
        <script>
            require(['jquery', 'jquery/ui'], function($){
                $( document ).ready(function() {
                    var existCondition = setInterval(function() {
                        if ($('#co-shipping-form input[name="region"]').length) {
                            clearInterval(existCondition);
                            $('#co-shipping-form input[name="region"]').parent().parent().addClass(window.checkoutConfig.shipping_region_class);
                            var additional = window.checkoutConfig.shipping_region_additional_class;
                            if(additional.length > 0) {
                                additional.forEach( function(classes) {
                                    $('#co-shipping-form input[name="region"]').parent().parent().addClass(classes);
                                })
                            }
                        }
                    }, 100);
                });
            });
        </script>
    </div>
</div>