<?php
/**
 * Mavenbird Technologies Private Limited
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://mavenbird.com/Mavenbird-Module-License.txt
 *
 * =================================================================
 *
 * @category   Mavenbird
 * @package    Mavenbird_Sorting
 * @author     Mavenbird Team
 * @copyright  Copyright (c) 2018-2024 Mavenbird Technologies Private Limited ( http://mavenbird.com )
 * @license    http://mavenbird.com/Mavenbird-Module-License.txt
 */
?>

<div class="userguide-container" style="border:dotted 1px #ccc; padding:20px;">


    <div id="messages">
        <ul class="messages">
            <li class="message message-notice notice" style="list-style: none;">
                <ul>
                    <li style="list-style: none;">For custom theme User:</li>
                </ul>
            </li>
        </ul>
    </div>



    <pre>
<code><strong>File Path:</strong> app\code\Mavenbird\OneStepCheckout\view\frontend\layout\onestepcheckout.xml</code>
<code>
 If you are facing issue related to deteriorate styles and you have installed custom theme then some of theme providers remove default styles of Magento,<br> In that case please go to the above path and uncomment included style "md-onestepcheckout.css" from the head tag.


</code>
    </pre>
 
</div>
